WITH 
grouped_table AS (
	select
		*,
		count("NO") over ( ORDER BY id ) AS _grp
	FROM
		{{ ref('stg_raw_activities') }}
	),
final_table AS ( 
	SELECT grouped_table.*, 
				first_value("NO") 
						over ( PARTITION BY _grp ORDER BY id ) AS ffill_NO 
	FROM grouped_table 
	),
raw_activities AS (
	SELECT
		id,
		SITE,
		"MONTH",
		"LOKASI UNIT",
		TRIM("SECTION") AS "SECTION",
		ffill_NO AS "NO",
		EGI,
		"CODE NUMBER UNIT", 
		HM,
		"PROBLEM DESCRIPTION",
		TRIM(UPPER(CASE 
			WHEN TRIM("PROBLEM DESCRIPTION") LIKE '%TYRE%NO%' or TRIM("PROBLEM DESCRIPTION") LIKE '%ADJUST%TYRE%'  or TRIM("PROBLEM DESCRIPTION") LIKE '%REP%TYRE%' then TRIM("PROBLEM DESCRIPTION")  
			else SPLIT_PART(regexp_replace(TRIM("PROBLEM DESCRIPTION"),'[+++]',','),',',1)
			end )) as PROBLEM_1,
		TRIM(UPPER(CASE 
			WHEN TRIM("PROBLEM DESCRIPTION") LIKE '%TYRE%NO%' or TRIM("PROBLEM DESCRIPTION") LIKE '%ADJUST%TYRE%'  or TRIM("PROBLEM DESCRIPTION") LIKE '%REP%TYRE%' then TRIM("PROBLEM DESCRIPTION")  
			else SPLIT_PART(regexp_replace(TRIM("PROBLEM DESCRIPTION"),'[+++]',','),',',2)
			end )) as PROBLEM_2,
		TRIM(UPPER(CASE 
			WHEN TRIM("PROBLEM DESCRIPTION") LIKE '%TYRE%NO%' or TRIM("PROBLEM DESCRIPTION") LIKE '%ADJUST%TYRE%'  or TRIM("PROBLEM DESCRIPTION") LIKE '%REP%TYRE%' then TRIM("PROBLEM DESCRIPTION")  
			else SPLIT_PART(regexp_replace(TRIM("PROBLEM DESCRIPTION"),'[+++]',','),',',3)
			end )) as PROBLEM_3,
		"START B/D (DATE)",
		"START B/D (TIME)",
		case when "WO NUMBER" = '300500023435' then "START B/D (DATE)" ELSE
		CONCAT("START B/D (DATE)", ' ', "START B/D (TIME)") end AS "START B/D", --ADD COLUMN START B/D DATE
		"WO NUMBER",
		"WO / BD TYPE",
		"MAINTENANCE TYPE",
		"STATUS UNIT",
		"ACTION PROBLEM",
		TRIM(UPPER(CASE 
			WHEN "ACTION PROBLEM" LIKE '%TYRE%NO%' or "ACTION PROBLEM" LIKE '%ADJUST%TYRE%'  or "ACTION PROBLEM" LIKE '%REP%TYRE%' then "ACTION PROBLEM" 
			else SPLIT_PART(regexp_replace("ACTION PROBLEM",'[+++]',','),',',1)
			end )) as ACTION_1,
		TRIM(UPPER(CASE 
			WHEN "ACTION PROBLEM" LIKE '%TYRE%NO%' or "ACTION PROBLEM" LIKE '%ADJUST%TYRE%'  or "ACTION PROBLEM" LIKE '%REP%TYRE%' then "ACTION PROBLEM"  
			else SPLIT_PART(regexp_replace("ACTION PROBLEM",'[+++]',','),',',2)
			end )) as ACTION_2,
		TRIM(UPPER(CASE 
			WHEN "ACTION PROBLEM" LIKE '%TYRE%NO%' or "ACTION PROBLEM" LIKE '%ADJUST%TYRE%'  or "ACTION PROBLEM" LIKE '%REP%TYRE%' then "ACTION PROBLEM"  
			else SPLIT_PART(regexp_replace("ACTION PROBLEM",'[+++]',','),',',3)
			end )) as ACTION_3,
		TRIM(UPPER(CASE 
			WHEN "ACTION PROBLEM" LIKE '%TYRE%NO%' or "ACTION PROBLEM" LIKE '%ADJUST%TYRE%'  or "ACTION PROBLEM" LIKE '%REP%TYRE%' then "ACTION PROBLEM"  
			else SPLIT_PART(regexp_replace("ACTION PROBLEM",'[+++]',','),',',4)
		end )) as ACTION_4,
		TRIM(UPPER(CASE 
			WHEN "ACTION PROBLEM" LIKE '%TYRE%NO%' or "ACTION PROBLEM" LIKE '%ADJUST%TYRE%'  or "ACTION PROBLEM" LIKE '%REP%TYRE%' then "ACTION PROBLEM"  
			else SPLIT_PART(regexp_replace("ACTION PROBLEM",'[+++]',','),',',5)
		end )) as ACTION_5,
		TRIM(UPPER(CASE 
			WHEN "ACTION PROBLEM" LIKE '%TYRE%NO%' or "ACTION PROBLEM" LIKE '%ADJUST%TYRE%'  or "ACTION PROBLEM" LIKE '%REP%TYRE%' then "ACTION PROBLEM"  
			else SPLIT_PART(regexp_replace("ACTION PROBLEM",'[+++]',','),',',6)
		end )) as ACTION_6,
		TRIM(UPPER(CASE 
			WHEN "ACTION PROBLEM" LIKE '%TYRE%NO%' or "ACTION PROBLEM" LIKE '%ADJUST%TYRE%'  or "ACTION PROBLEM" LIKE '%REP%TYRE%' then "ACTION PROBLEM"  
			else SPLIT_PART(regexp_replace("ACTION PROBLEM",'[+++]',','),',',7)
		end )) as ACTION_7,
		TRIM(UPPER(CASE 
			WHEN "ACTION PROBLEM" LIKE '%TYRE%NO%' or "ACTION PROBLEM" LIKE '%ADJUST%TYRE%'  or "ACTION PROBLEM" LIKE '%REP%TYRE%' then "ACTION PROBLEM"  
			else SPLIT_PART(regexp_replace("ACTION PROBLEM",'[+++]',','),',',8)
		end )) as ACTION_8,
		TRIM(UPPER(CASE 
			WHEN "ACTION PROBLEM" LIKE '%TYRE%NO%' or "ACTION PROBLEM" LIKE '%ADJUST%TYRE%'  or "ACTION PROBLEM" LIKE '%REP%TYRE%' then "ACTION PROBLEM"  
			else SPLIT_PART(regexp_replace("ACTION PROBLEM",'[+++]',','),',',9)
		end )) as ACTION_9,
		"ACTIVITY CODE",
		"DESCRIPTION ACTIVITY",
		"START ACTIVITY (DATE)",
		"START ACTIVITY (TIME)",
		case when "WO NUMBER" = '300500023435' then "START ACTIVITY (DATE)" else
		CONCAT("START ACTIVITY (DATE)", ' ', "START ACTIVITY (TIME)") end AS "START ACTIVITY", -- ADD COLUMN START ACTIVITY DATE
		"FINISH ACTIVITY (DATE)",
		"FINISH ACTIVITY (TIME)",
		case when "WO NUMBER" = '300500023435' then "FINISH ACTIVITY (DATE)" else
		CONCAT("FINISH ACTIVITY (DATE)", ' ', "FINISH ACTIVITY (TIME)") end AS "FINISH ACTIVITY", -- ADD COLUMN FINISH ACTIVITY DATE
		"RFU (DATE)",
		"RFU (TIME)",
		case when "WO NUMBER" = '300500023435' then "RFU (DATE)" else
		CONCAT("RFU (DATE)", ' ', "RFU (TIME)") end AS "RFU", -- ADD COLUMN RFU DATE
		"AGING B/D (DAY)",
		"AGING B/D (HOUR)",
		"AGING ACTIVITY (DAY)",
		"AGING ACTIVITY (HOUR)",
		"SUB COMP CODE",
		"COMP CODE",
		TRIM(UPPER("DESCRIPTION SUB COMP (PA)")) AS "DESCRIPTION SUB COMP (PA)",
		TRIM(UPPER("DESRICTION COMP (PA)")) AS "DESRICTION COMP (PA)",
		TRIM(UPPER("DESCRIPTION SUB COMP (MTBF)")) AS "DESCRIPTION SUB COMP (MTBF)",
		TRIM(UPPER("DESRICTION COMP (MTBF)")) AS "DESRICTION COMP (MTBF)",
		"PIC MEKANIK / GROUP LEADER",
		TRIM(UPPER(SPLIT_PART("PIC MEKANIK / GROUP LEADER", ',', 1))) AS PIC_1,
		TRIM(UPPER(SPLIT_PART("PIC MEKANIK / GROUP LEADER", ',', 2))) AS PIC_2,
		TRIM(UPPER(SPLIT_PART("PIC MEKANIK / GROUP LEADER", ',', 3))) AS PIC_3,
		TRIM(UPPER(SPLIT_PART("PIC MEKANIK / GROUP LEADER", ',', 4))) AS PIC_4,
		TRIM(UPPER(SPLIT_PART("PIC MEKANIK / GROUP LEADER", ',', 5))) AS PIC_5,
		TRIM(UPPER(SPLIT_PART("PIC MEKANIK / GROUP LEADER", ',', 6))) AS PIC_6,
		"RO / PR NUMBER",
		"RO / PR (DATE)",
		"RO / PR (STATUS)",
		"PO NUMBER",
		"PO (DATE)",
		"PO (STATUS)",
		remark 
	FROM
		final_table 
	WHERE EGI = 'EGI 12' -- FILTER EGI
	),
raw_activities_ AS (
										SELECT id, SITE, "MONTH", "LOKASI UNIT" AS LOKASI_UNIT,
										 "SECTION", "NO", EGI, "CODE NUMBER UNIT" AS CODE_NUMBER_UNIT,
										 HM, TRIM("PROBLEM DESCRIPTION") AS PROBLEM_DESCRIPTION,PROBLEM_1 AS PROBLEM_1,
											CASE WHEN PROBLEM_1 = PROBLEM_2 THEN NULL ELSE PROBLEM_2 END AS PROBLEM_2,
											CASE WHEN PROBLEM_2 = PROBLEM_3 THEN NULL ELSE PROBLEM_3 END AS PROBLEM_3,
											"START B/D (DATE)" AS START_BD_DATE,
											"START B/D (TIME)" AS START_BD_TIME,
											"START B/D" AS START_BD,
											"WO NUMBER" AS WO_NUMBER,
											"WO / BD TYPE" AS WO_BD_TYPE,
											"MAINTENANCE TYPE" AS MAINTENANCE_TYPE,
											"STATUS UNIT" AS STATUS_UNIT,
											"ACTION PROBLEM" AS ACTION_PROBLEM, 
											ACTION_1 AS ACTION_1_,
											CASE WHEN ACTION_1 = ACTION_2 THEN NULL ELSE ACTION_2 END AS ACTION_2_,
											CASE WHEN ACTION_2 = ACTION_3 THEN NULL ELSE ACTION_3 END AS ACTION_3_,
											CASE WHEN ACTION_3 = ACTION_4 THEN NULL ELSE ACTION_4 END AS ACTION_4_,
											CASE WHEN ACTION_4 = ACTION_5 THEN NULL ELSE ACTION_5 END AS ACTION_5_,
											CASE WHEN ACTION_5 = ACTION_6 THEN NULL ELSE ACTION_6 END AS ACTION_6_,
											CASE WHEN ACTION_6 = ACTION_7 THEN NULL ELSE ACTION_7 END AS ACTION_7_,
											CASE WHEN ACTION_7 = ACTION_8 THEN NULL ELSE ACTION_8 END AS ACTION_8_,
											CASE WHEN ACTION_8 = ACTION_9 THEN NULL ELSE ACTION_9 END AS ACTION_9_,
												"ACTIVITY CODE" AS ACTIVITY_CODE,
												"DESCRIPTION ACTIVITY" AS DESCRIPTION_ACTIVITY,
												"START ACTIVITY (DATE)" AS START_ACTIVITY_DATE,
												"START ACTIVITY (TIME)" AS START_ACTIVITY_TIME,
												"START ACTIVITY" AS START_ACTIVITY, -- ADD COLUMN START ACTIVITY DATE
												"FINISH ACTIVITY (DATE)" AS FINISH_ACTIVITY_DATE,
												"FINISH ACTIVITY (TIME)" AS FINISH_ACTIVITY_TIME,
												"FINISH ACTIVITY" AS FINISH_ACTIVITY, -- ADD COLUMN FINISH ACTIVITY DATE
												"RFU (DATE)" AS RFU_DATE,
												"RFU (TIME)"AS RFU_TIME,
												"RFU", -- ADD COLUMN RFU DATE
												"AGING B/D (DAY)" AS AGING_BD_DAY,
												"AGING B/D (HOUR)" AS AGING_BD_HOUR,
												"AGING ACTIVITY (DAY)" AS AGING_ACTIVITY_DAY,
												"AGING ACTIVITY (HOUR)" AS AGING_ACTIVITY_HOUR,
												"SUB COMP CODE" AS SUB_COMP_CODE,
												"COMP CODE" AS COMP_CODE,
												"DESCRIPTION SUB COMP (PA)" AS DESC_SUB_COMP_PA,
												"DESRICTION COMP (PA)"AS DESC_COMP_PA,
												"DESCRIPTION SUB COMP (MTBF)"AS DESC_SUB_COMP_MTBF,
												"DESRICTION COMP (MTBF)"AS DESC_COMP_MTBF,
												"PIC MEKANIK / GROUP LEADER" AS PIC,
												PIC_1 AS PIC_1_,
												CASE WHEN PIC_1 = PIC_2 THEN NULL ELSE PIC_2 END AS PIC_2_,
												CASE WHEN PIC_2 = PIC_3 THEN NULL ELSE PIC_3 END AS PIC_3_,
												CASE WHEN PIC_3 = PIC_4 THEN NULL ELSE PIC_4 END AS PIC_4_,
												CASE WHEN PIC_4 = PIC_5 THEN NULL ELSE PIC_5 END AS PIC_5_,
												CASE WHEN PIC_5 = PIC_6 THEN NULL ELSE PIC_6 END AS PIC_6_,
												remark 
										FROM raw_activities
										WHERE "ACTIVITY CODE" IS NOT NULL -- TERDAPAT 1 NULL
										)
SELECT * FROM raw_activities_
ORDER BY START_BD, START_ACTIVITY, CODE_NUMBER_UNIT